[package]
name = "wasmlanche-cosmwasm-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { version = "1.5.0", default-features = false }
cosmwasm-storage = { version = "1.5.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
wasmlanche = { path = "../../hyper/x/contracts/wasmlanche" }
execution-interface = { path = "../interface" }
borsh = { version = "1.2.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
cosmwasm-schema = "1.5.0"
