[workspace]
resolver = "2"  # Using resolver 2 for edition 2021 compatibility

members = [
    "interface",
    "wasm-module",
    "controller",
    "contract"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tal <tal@rhombus-tech.com>"]
description = "Dual TEE execution system using Enarx"

[workspace.dependencies]
# Serialization
borsh = { version = "0.10", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async
tokio = { version = "1.0", features = ["full"] }

# TEE/Enarx
sallyport = "0.1.0"

# Crypto
sha2 = "0.10"

# Error handling
thiserror = "1.0"

# WASM
wasm-bindgen = "0.2"