[workspace]
resolver = "2"  
members = [
    "interface",
    "controller",
    "wasm-module",
    "hyper"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tal <tal@rhombus-tech.com>"]
description = "Dual TEE execution system using Enarx"

[workspace.dependencies]
# Serialization
borsh = "0.10"
borsh-derive = "0.10.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Error handling
thiserror = "1.0"

# Logging
log = "0.4"

# Crypto
sha2 = "0.10"
