[package]
name = "wasm_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmlanche = { path = "../../../../../hyper/x/contracts/wasmlanche", default-features = false, features = ["wasm"] }
