[package]
name = "tee-wasm-module"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]  # Compile as dynamic library for WASM

[dependencies]
borsh.workspace = true
borsh-derive = "0.10.3"
tee-interface = { path = "../interface" }
sha2.workspace = true
thiserror = "1.0"
log = "0.4"

[dev-dependencies]