[package]
name = "tee-interface"
version.workspace = true
edition.workspace = true

[dependencies]
# Serialization
borsh = { workspace = true, features = ["derive"] }
borsh-derive = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Crypto
sha2 = { workspace = true }

# Async
async-trait = { workspace = true }