[package]
name = "tee-interface"
version.workspace = true
edition.workspace = true

[dependencies]
# Serialization
borsh = "0.10.3"
borsh-derive = "0.10.3"

# Error handling
thiserror = { workspace = true }

# Crypto
sha2 = { workspace = true }

# Async
async-trait = { workspace = true }