[package]
name = "tee-controller"
version.workspace = true
edition.workspace = true

[dependencies]
# Our interface
tee-interface = { path = "../interface" }

# Core deps
tokio = { version = "1.0", features = ["full", "macros"] }
borsh = { version = "1.5.1", features = ["derive", "std"] }
borsh-derive = { version = "1.5.1" }
async-trait = "0.1"

# gRPC
tonic = { version = "0.10", features = ["transport", "codegen"] }
prost = "0.12"
tower = "0.4"

# CLI
clap = { version = "4.4", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Error handling
thiserror = "1.0"

# Crypto
sha2 = "0.10"

# Time
chrono = "0.4"

# Utils
rand = "0.8"
tempfile = "3.8"

[build-dependencies]
tonic-build = "0.10"

[dev-dependencies]
tokio-test = "0.4"