[package]
name = "tee-controller"
version.workspace = true
edition.workspace = true

[dependencies]
# Our interface
tee-interface = { path = "../interface" }

# Core deps
tokio = { version = "1.0", features = ["full"] }
borsh.workspace = true
borsh-derive = "0.10.3"
async-trait.workspace = true

# CLI
clap = { version = "4.0", features = ["derive"] }

# Error handling
thiserror.workspace = true

# Crypto
sha2.workspace = true

# Utils
rand = "0.8"
tempfile = "3.8"

[dev-dependencies]
tokio-test = "0.4"