[package]
name = "tee-controller"
version.workspace = true
edition.workspace = true

[dependencies]
# Our interface
tee-interface = { path = "../interface" }

# Core deps
tokio = { version = "1.0", features = ["full"] }
borsh.workspace = true
borsh-derive = "0.10.3"
async-trait.workspace = true

# CLI
clap = { version = "4.0", features = ["derive"] }

# Error handling
thiserror.workspace = true

# Crypto
sha2.workspace = true

# Utils
rand = "0.8"
tempfile = "3.8"

# Logging
log = "0.4"

# HTTP calls
reqwest = { version = "0.11", features = ["json"] }

# Retry
tokio-retry = "0.3"

# Metrics and logging
metrics = "0.20"
metrics-exporter-prometheus = "0.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
time = { version = "0.3", features = ["formatting"] }

# Added hex dependency for contract ID encoding
hex = "0.4"

[dev-dependencies]
tokio-test = "0.4"